// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// doLARS2D
List doLARS2D(SEXP R_Y, SEXP R_maxBreaks, SEXP R_maxVar, SEXP R_verbose, SEXP R_Beta);
RcppExport SEXP blockseg_doLARS2D(SEXP R_YSEXP, SEXP R_maxBreaksSEXP, SEXP R_maxVarSEXP, SEXP R_verboseSEXP, SEXP R_BetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type R_Y(R_YSEXP);
    Rcpp::traits::input_parameter< SEXP >::type R_maxBreaks(R_maxBreaksSEXP);
    Rcpp::traits::input_parameter< SEXP >::type R_maxVar(R_maxVarSEXP);
    Rcpp::traits::input_parameter< SEXP >::type R_verbose(R_verboseSEXP);
    Rcpp::traits::input_parameter< SEXP >::type R_Beta(R_BetaSEXP);
    __result = Rcpp::wrap(doLARS2D(R_Y, R_maxBreaks, R_maxVar, R_verbose, R_Beta));
    return __result;
END_RCPP
}
// Xprod
NumericVector Xprod(SEXP R_Y);
RcppExport SEXP blockseg_Xprod(SEXP R_YSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type R_Y(R_YSEXP);
    __result = Rcpp::wrap(Xprod(R_Y));
    return __result;
END_RCPP
}
